name: Compila Typst

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installa Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: '0.13.1'

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin master

      - name: runna bash
        run: | 
          chmod +x compile.sh
          ./compile.sh

      - name: Check Git status
        run: git status
      
      - name: Add, commit and push changes
        run: |
          git add .
          git commit -m "PDF compilato [bot]"
          git push
