name: Compile Typst

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: '0.13.1'

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          
      - name: Run bash
        run: | 
          chmod +x compile.sh
          ./compile.sh

      - name: Check Git status
        run: git status
      
      - name: Upload website and PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-pdf-files
          path: website/
          retention-days: 1
          if-no-files-found: error

  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Download website files and PDFs artifact
          uses: actions/download-artifact@v4
          with:
            name: website-pdf-files
            path: website/

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.24.3'

        - name: Install Go dependencies
          run: go mod tidy
          working-directory: script/

        - name: Render HTML with Go
          run: go run renderHTMLwithPDFs.go
          working-directory: script/

        - name: Configure GitHub Pages
          uses: actions/configure-pages@v5

        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: website/

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4